import { Resource } from 'i18next';

export const locales = ['it', 'en'] as const;

export const defaultLocale = process.env.DEFAULT_LOCALE || 'it';

export const defaultMarket = process.env.DEFAULT_MARKET || 'ww';

export const group = {
  content: 'content',
  nav: 'nav',
  actions: 'actions',
  gdpr: 'gdpr',
  users: 'users',
  config: 'config',
  i18n: 'i18n',
};

export const slug = {
  category: 'category',
  legal_notice: 'legal_notice',
  homepage: 'homepage',
  cultura_index: 'cultura_index',
  cultura_detail: 'cultura_detail',
  industry_index: 'industry_index',
  industry_detail: 'industry_detail',
  product_category: 'product_category',
  product_detail: 'product_detail',
  project_index: 'project_index',
  project_detail: 'project_detail',
  location_index: 'location_index',
  location_detail: 'location_detail',
  about: 'about',
  contact: 'contact',
  newsletter: 'newsletter',
  job: 'job',
  legal_document: 'legal_document',
  banner: 'banner',
  client: 'client',
  company: 'company',
  person: 'person',
  work_role: 'work_role',
  color: 'color',
  media: 'media',
  users: 'users',
  endUsers: 'end_users',
  consentPreference: 'consent_preference',
  contact_us_action: 'contact_us_action',
  newsletter_action: 'newsletter_action',
};

export const pages = [
  slug.homepage,
  slug.cultura_index,
  slug.cultura_detail,
  slug.industry_index,
  slug.industry_detail,
  slug.product_category,
  slug.product_detail,
  slug.project_index,
  slug.project_detail,
  slug.location_index,
  slug.location_detail,
  slug.about,
  slug.contact,
  slug.newsletter,
  slug.job,
  slug.legal_document,
];

export const roles = {
  Admin: 'admin',
  Contributor: 'contributor',
  Editor: 'editor',
  Translator: 'translator',
  Guest: 'guest',
  User: 'user',
  Press: 'press',
} as const;

export const translations: Resource = {
  en: {
    collection: {
      singular: {
        homepage: 'Homepage',
        cultura_index: 'Culture Index',
        cultura_detail: 'Culture Detail',
        industry_index: 'Industry Index',
        industry_detail: 'Industry Detail',
        product_category: 'Product Category',
        product_detail: 'Product Detail',
        project_index: 'Project Index',
        project_detail: 'Project Detail',
        location_index: 'Location Index',
        location_detail: 'Location Detail',
        about: 'About',
        contact: 'Contact',
        newsletter: 'Newsletter',
        job: 'Job',
        legal_document: 'Legal Document',
        banner: 'Banner',
        client: 'Client',
        company: 'Company',
        person: 'Person',
        work_role: 'Work Role',
        color: 'Color',
        contact_us_action: 'Contact Us',
        newsletter_action: 'Newsletter',
        users: 'User',
        'cultura-content': 'Culture Content',
        'intro-1': 'Intro 1',
        'cultura-callout': 'Culture Callout',
        'cultura-image': 'Culture Image',
        'cultura-slider': 'Culture Slider',
        'cultura-video': 'Culture Video',
        'detail-1': 'Detail 1',
        'gallery-1': 'Gallery 1',
        'highlights-1': 'Highlights 1',
        'media-box-1': 'Media Box 1',
        'text-combo-1': 'Text Combo 1',
        'image-mask-1': 'Image Mask 1',
        'media-double-1': 'Media Double 1',
        'media-drawer-1': 'Media Drawer 1',
        'media-split-1': 'Media Split 1',
        'overview-1': 'Overview 1',
        'quote-1': 'Quote 1',
        'side-images-1': 'Side Images 1',
        'title-box-1': 'Title Box 1',
        'blog-more-1': 'Blog More 1',
        'carousel-1': 'Carousel 1',
        'cover-1': 'Cover 1',
        'folder-1': 'Folder 1',
        'hero-1': 'Hero 1',
        'media-tabs-1': 'Media Tabs 1',
        'more-1': 'More 1',
        'project-alphabetically': 'Project Alphabetically',
        'project-selection': 'Project Selection',
        'project-tag': 'Project Tag',
        'project-type': 'Project Type',
        'spotlight-1': 'Spotlight 1',
        'text-columns-1': 'Text Columns 1',
        'text-tabs-1': 'Text Tabs 1',
        'folder-accordion': 'Folder Accordion',
        'folder-hive': 'Folder Hive',
        'folder-media': 'Folder Media',
        'folder-pie': 'Folder Pie',
        'text-combo-slider-1': 'Text Combo Slider 1',
        'circular-slider': 'Circular Slider',
        'callout': 'Callout',
        'location-more': 'Location More',
        'media-slider': 'Media Slider',
        'cultura-youtube': 'Culture Youtube',
        'media-youtube': 'Media Youtube',
        'card-list': 'Card List',
        'media-slider-grid': 'Media Slider Grid',
        'text-list': 'Text List',
        'text-big': 'Text Big',
        'media-video': 'Media Video',
        'project-more': 'Project More',
        'industry-more': 'Industry More',
        'media-loop': 'Media Loop',
        'cover-main': 'Cover Main',
        'spotlight-slider': 'Spotlight Slider',
        'overview-info': 'Overview Info',
        'overview-service': 'Overview Service',
        'overview-team': 'Overview Team',
      },
      plural: {
        homepage: 'Homepage',
        cultura_index: 'Culture Index',
        cultura_detail: 'Culture Detail',
        industry_index: 'Industry Index',
        industry_detail: 'Industry Detail',
        product_category: 'Product Category',
        product_detail: 'Product Detail',
        project_index: 'Project Index',
        project_detail: 'Project Detail',
        location_index: 'Location Index',
        location_detail: 'Location Detail',
        about: 'About',
        contact: 'Contact',
        newsletter: 'Newsletter',
        job: 'Job',
        legal_document: 'Legal Document',
        banner: 'Banner',
        client: 'Client',
        company: 'Company',
        person: 'Person',
        work_role: 'Work Role',
        color: 'Colors',
        contact_us_action: 'Contact Us',
        newsletter_action: 'Newsletter',
        users: 'User',
        'cultura-content': 'Culture Content',
        'intro-1': 'Intro 1',
        'cultura-callout': 'Culture Callout',
        'cultura-image': 'Culture Image',
        'cultura-slider': 'Culture Slider',
        'cultura-video': 'Culture Video',
        'detail-1': 'Detail 1',
        'gallery-1': 'Gallery 1',
        'highlights-1': 'Highlights 1',
        'media-box-1': 'Media Box 1',
        'text-combo-1': 'Text Combo 1',
        'image-mask-1': 'Image Mask 1',
        'media-double-1': 'Media Double 1',
        'media-drawer-1': 'Media Drawer 1',
        'media-split-1': 'Media Split 1',
        'overview-1': 'Overview 1',
        'quote-1': 'Quote 1',
        'side-images-1': 'Side Images 1',
        'title-box-1': 'Title Box 1',
        'blog-more-1': 'Blog More 1',
        'carousel-1': 'Carousel 1',
        'cover-1': 'Cover 1',
        'folder-1': 'Folder 1',
        'hero-1': 'Hero 1',
        'media-tabs-1': 'Media Tabs 1',
        'more-1': 'More 1',
        'project-alphabetically': 'Project Alphabetically',
        'project-selection': 'Project Selection',
        'project-tag': 'Project Tag',
        'project-type': 'Project Type',
        'spotlight-1': 'Spotlight 1',
        'text-columns-1': 'Text Columns 1',
        'text-tabs-1': 'Text Tabs 1',
        'folder-accordion': 'Folder Accordion',
        'folder-hive': 'Folder Hive',
        'folder-media': 'Folder Media',
        'folder-pie': 'Folder Pie',
        'text-combo-slider-1': 'Text Combo Slider 1',
        'circular-slider': 'Circular Slider',
        'callout': 'Callout',
        'location-more': 'Location More',
        'media-slider': 'Media Slider',
        'cultura-youtube': 'Culture Youtube',
        'media-youtube': 'Media Youtube',
        'card-list': 'Card List',
        'media-slider-grid': 'Media Slider Grid',
        'text-list': 'Text List',
        'text-big': 'Text Big',
        'media-video': 'Media Video',
        'project-more': 'Project More',
        'industry-more': 'Industry More',
        'media-loop': 'Media Loop',
        'cover-main': 'Cover Main',
        'spotlight-slider': 'Spotlight Slider',
        'overview-info': 'Overview Info',
        'overview-service': 'Overview Service',
        'overview-team': 'Overview Team',
      },
    },
    field: {
      archived: 'Archived',
      colorScheme: 'Color Scheme',
      layout: 'Layout',
      titleSize: 'Title Size',
      author: 'Author',
      thumb: 'Thumbnail',
      bottomBorder: 'Bottom Border',
      eyelet: 'Eyelet',
      innerSpace: 'Inner Space',
      list: 'List',
      swap: 'Swap',
      topSpace: 'Top Space',
      wrapper: 'Wrapper',
      modal: 'Modal',
      partners: 'Partners',
      selection: 'Selection',
      navs: 'Links',
      anchor: 'Anchor',
      seoWeight: 'SEO Weight',
      active: 'Active',
      categories: 'Categories',
      counter: 'Counter',
      cta: 'CTA',
      left: 'Left',
      quantity: 'Quantity',
      tag: 'Tag',
      top: 'Top',
      components: 'Components',
      dots: 'Dots',
      mediaRadius: 'Media Radius',
      mediaSmall: 'Media Small',
      features: 'Features',
      fromDate: 'From',
      toDate: 'To',
      projects: 'Projects',
      client: 'Client',
      hash: 'Slug',
      firstName: 'Nome',
      lastName: 'Cognome',
      userData: 'Dati utente',
      clients: 'Clients',
      companies: 'Companies',
      banner: 'Banner',
      fullName: 'Full Name',
      role: 'Role',
      company: 'Company',
      className: 'Class Name',
      itemsList: 'Numbered List',
      mediaColor: 'Media Color Scheme',
      colorData: 'Color',
      src: 'Src',
      hero: 'Hero',
      budget: 'Budget',
      companyArea: 'Company Area',
      companyName: 'Company Name',
      message: 'Message',
      options: 'Options',
      request: 'Request',
      service: 'Service',
      legal_notice: 'Legal Notice',
      gallery: 'Gallery',
      scrollToAnchor: 'Scroll To Anchor',
      speed: 'Speed',
      startingIndex: 'Starting Index',
      member: 'Member',
    },
  },
  it: {
    collection: {
      singular: {
        homepage: 'Homepage',
        cultura_index: 'Cultura Index',
        cultura_detail: 'Cultura Detail',
        industry_index: 'Industry Index',
        industry_detail: 'Industry Detail',
        product_category: 'Product Category',
        product_detail: 'Product Detail',
        project_index: 'Project Index',
        project_detail: 'Project Detail',
        location_index: 'Location Index',
        location_detail: 'Location Detail',
        about: 'About',
        contact: 'Contact',
        newsletter: 'Newsletter',
        job: 'Job',
        legal_document: 'Documento Legale',
        banner: 'Banner',
        client: 'Cliente',
        company: 'Company',
        person: 'Persona',
        work_role: 'Ruolo Aziendale',
        color: 'Colore',
        contact_us_action: 'Contact Us',
        newsletter_action: 'Newsletter',
        users: 'Utente',
        'cultura-content': 'Cultura Content',
        'intro-1': 'Intro 1',
        'cultura-callout': 'Cultura Callout',
        'cultura-image': 'Cultura Image',
        'cultura-slider': 'Cultura Slider',
        'cultura-video': 'Cultura Video',
        'detail-1': 'Detail 1',
        'gallery-1': 'Gallery 1',
        'highlights-1': 'Highlights 1',
        'media-box-1': 'Media Box 1',
        'text-combo-1': 'Text Combo 1',
        'image-mask-1': 'Image Mask 1',
        'media-double-1': 'Media Double 1',
        'media-drawer-1': 'Media Drawer 1',
        'media-split-1': 'Media Split 1',
        'overview-1': 'Overview 1',
        'quote-1': 'Quote 1',
        'side-images-1': 'Side Images 1',
        'title-box-1': 'Title Box 1',
        'blog-more-1': 'Blog More 1',
        'carousel-1': 'Carousel 1',
        'cover-1': 'Cover 1',
        'folder-1': 'Folder 1',
        'hero-1': 'Hero 1',
        'media-tabs-1': 'Media Tabs 1',
        'more-1': 'More 1',
        'project-alphabetically': 'Project Alphabetically',
        'project-selection': 'Project Selection',
        'project-tag': 'Project Tag',
        'project-type': 'Project Type',
        'spotlight-1': 'Spotlight 1',
        'text-columns-1': 'Text Columns 1',
        'text-tabs-1': 'Text Tabs 1',
        'folder-accordion': 'Folder Accordion',
        'folder-hive': 'Folder Hive',
        'folder-media': 'Folder Media',
        'folder-pie': 'Folder Pie',
        'text-combo-slider-1': 'Text Combo Slider 1',
        'circular-slider': 'Circular Slider',
        'callout': 'Callout',
        'location-more': 'Location More',
        'media-slider': 'Media Slider',
        'cultura-youtube': 'Culture Youtube',
        'media-youtube': 'Media Youtube',
        'card-list': 'Card List',
        'media-slider-grid': 'Media Slider Grid',
        'text-list': 'Text List',
        'text-big': 'Text Big',
        'media-video': 'Media Video',
        'project-more': 'Project More',
        'industry-more': 'Industry More',
        'media-loop': 'Media Loop',
        'cover-main': 'Cover Main',
        'spotlight-slider': 'Spotlight Slider',
        'overview-info': 'Overview Info',
        'overview-service': 'Overview Service',
        'overview-team': 'Overview Team',
      },
      plural: {
        homepage: 'Homepage',
        cultura_index: 'Cultura Index',
        cultura_detail: 'Cultura Detail',
        industry_index: 'Industry Index',
        industry_detail: 'Industry Detail',
        product_category: 'Product Category',
        product_detail: 'Product Detail',
        project_index: 'Project Index',
        project_detail: 'Project Detail',
        location_index: 'Location Index',
        location_detail: 'Location Detail',
        about: 'About',
        contact: 'Contact',
        newsletter: 'Newsletter',
        job: 'Job',
        legal_document: 'Documenti Legali',
        banner: 'Banner',
        client: 'Clienti',
        company: 'Companies',
        person: 'Persone',
        work_role: 'Ruoli Aziendali',
        color: 'Colori',
        contact_us_action: 'Contact Us',
        newsletter_action: 'Newsletter',
        users: 'Utenti',
        'cultura-content': 'Cultura Content',
        'intro-1': 'Intro 1',
        'cultura-callout': 'Cultura Callout',
        'cultura-image': 'Cultura Image',
        'cultura-slider': 'Cultura Slider',
        'cultura-video': 'Cultura Video',
        'detail-1': 'Detail 1',
        'gallery-1': 'Gallery 1',
        'highlights-1': 'Highlights 1',
        'media-box-1': 'Media Box 1',
        'text-combo-1': 'Text Combo 1',
        'image-mask-1': 'Image Mask 1',
        'media-double-1': 'Media Double 1',
        'media-drawer-1': 'Media Drawer 1',
        'media-split-1': 'Media Split 1',
        'overview-1': 'Overview 1',
        'quote-1': 'Quote 1',
        'side-images-1': 'Side Images 1',
        'title-box-1': 'Title Box 1',
        'blog-more-1': 'Blog More 1',
        'carousel-1': 'Carousel 1',
        'cover-1': 'Cover 1',
        'folder-1': 'Folder 1',
        'hero-1': 'Hero 1',
        'media-tabs-1': 'Media Tabs 1',
        'more-1': 'More 1',
        'project-alphabetically': 'Project Alphabetically',
        'project-selection': 'Project Selection',
        'project-tag': 'Project Tag',
        'project-type': 'Project Type',
        'spotlight-1': 'Spotlight 1',
        'text-columns-1': 'Text Columns 1',
        'text-tabs-1': 'Text Tabs 1',
        'folder-accordion': 'Folder Accordion',
        'folder-hive': 'Folder Hive',
        'folder-media': 'Folder Media',
        'folder-pie': 'Folder Pie',
        'text-combo-slider-1': 'Text Combo Slider 1',
        'circular-slider': 'Circular Slider',
        'callout': 'Callout',
        'location-more': 'Location More',
        'media-slider': 'Media Slider',
        'cultura-youtube': 'Culture Youtube',
        'media-youtube': 'Media Youtube',
        'card-list': 'Card List',
        'media-slider-grid': 'Media Slider Grid',
        'text-list': 'Text List',
        'text-big': 'Text Big',
        'media-video': 'Media Video',
        'project-more': 'Project More',
        'industry-more': 'Industry More',
        'media-loop': 'Media Loop',
        'cover-main': 'Cover Main',
        'spotlight-slider': 'Spotlight Slider',
        'overview-info': 'Overview Info',
        'overview-service': 'Overview Service',
        'overview-team': 'Overview Team',
      },
    },
    field: {
      archived: 'Archiviato',
      colorScheme: 'Schema di colori',
      layout: 'Layout',
      titleSize: 'Dimensione del titolo',
      author: 'Autore',
      thumb: 'Miniatura',
      bottomBorder: 'Bordo inferiore',
      eyelet: 'Occhiello',
      innerSpace: 'Spazio interno',
      list: 'Lista',
      swap: 'Scambia',
      topSpace: 'Spazio superiore',
      wrapper: 'Wrapper',
      modal: 'Modale',
      partners: 'Partners',
      selection: 'Selection',
      navs: 'Collegamenti',
      anchor: 'Ancora',
      seoWeight: 'Peso SEO',
      active: 'Attivo',
      categories: 'Categorie',
      counter: 'Contatore',
      cta: 'CTA',
      left: 'Sinistra',
      quantity: 'Quantità',
      tag: 'Tag',
      top: 'Top',
      components: 'Componenti',
      dots: 'Punti',
      mediaRadius: 'Media Radius',
      mediaSmall: 'Media Piccolo',
      features: 'Caratteristiche',
      fromDate: 'Da',
      toDate: 'A',
      projects: 'Progetti',
      client: 'Cliente',
      hash: 'Slug',
      firstName: 'Nome',
      lastName: 'Cognome',
      userData: 'Dati utente',
      clients: 'Clienti',
      companies: 'Companies',
      banner: 'Banner',
      fullName: 'Nome completo',
      role: 'Ruolo',
      company: 'Company',
      className: 'Nome classe',
      itemsList: 'Lista numerata',
      mediaColor: 'Schema di colori del Media',
      colorData: 'Colore',
      src: 'Src',
      hero: 'Hero',
      budget: 'Budget',
      companyArea: 'Area aziendale',
      companyName: 'Nome azienda',
      message: 'Messaggio',
      options: 'Opzioni',
      request: 'Richiesta',
      service: 'Servizio',
      legal_notice: 'Informativa legale',
      gallery: 'Galleria',
      scrollToAnchor: 'Scorri all\'ancora',
      speed: 'Velocità',
      startingIndex: 'Indice di partenza',
      member: 'Membro',
    },
  },
};
